name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.0', '8.1', '8.2', '8.3'] # Specify the PHP versions you want to test
    steps:
    - uses: actions/checkout@v3
      
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
        coverage: none

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    
    - name: Run Test
      run: ./vendor/bin/phpunit

    - name: Generate Badge
      if: success()
      uses: schneegans/dynamic-badges-action@v1.4.0
      with:
        auth: ${{ secrets.SHIELDS_IO_API_TOKEN }} 
        label: Tests (PHP ${{ matrix.php-version }}) 
        message: Passing
        color: green
        namedLogo: phpunit
        output: tests-badge-${{ matrix.php-version }}.svg

    - name: Commit badge
      uses: EndBug/add-and-commit@v9
      with:
        add: 'tests-badge-*.svg'
        message: 'Update test badges'
