name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.0', '8.1', '8.2', '8.3'] # Specify the PHP versions you want to test
    steps:
    - uses: actions/checkout@v3
      
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
        coverage: none

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    
    - name: Run Test
      run: ./vendor/bin/phpunit

    # Generate a badge if tests pass
    - name: Create Test Passed Badge
      if: success()
      uses: schneegans/dynamic-badges-action@v1.5.0
      with:
        auth: ${{ secrets.GITHUB_TOKEN }}
        token: ${{ secrets.GITHUB_TOKEN }}
        filename: test-passed-badge-${{ matrix.php-version }}.svg
        label: "Tests PHP ${{ matrix.php-version }}"
        message: Passed
        color: brightgreen

    # Upload the badge to the repository
    - name: Upload Badge
      if: success()
      run: |
        mv test-passed-badge-${{ matrix.php-version }}.svg public/
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add public/test-passed-badge-${{ matrix.php-version }}.svg
        git commit -m "Add test passed badge for PHP ${{ matrix.php-version }}"
        git push